spring.application.name=analytical-service

server.port=8082

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized

spring.mongodb.uri=mongodb://localhost:27017/analytical_db
# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=analytical-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=org.portfolio.analyticalservice.event.TransactionCreatedEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=org.portfolio.analyticalservice.event

topic.name=transaction-events
